#!/usr/bin/python

import BaseHTTPServer as http
import signal

class MockBaseServer(http.BaseHTTPRequestHandler):
    BODY = b'{ "mockbase": "ftw" }'

    def do_HEAD(self):
        self.write_response()

    def do_GET(self):
        self.write_response()
        self.write_body()

    def do_POST(self):
        self.write_response()
        self.write_body()

    def write_response(self):
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.send_header('Content-length', len(self.BODY))
        self.end_headers()

    def write_body(self):
        self.wfile.write(self.BODY)

server = http.HTTPServer(('', 1134), MockBaseServer)

def reload(signum, frame):
    print("Config reloaded")

signal.signal(signal.SIGHUP, reload)

server.serve_forever()
